swagger: '2.0'
info:
  title: CFGM
  version: v0.1.0
host: 'localhost:9000'
schemes:
  - http
basePath: /
paths:
  /cfg:
    post:
      description: 'Get config'
      consumes:
        - application/json
      parameters:
        - required: true
          schema:
            $ref: "#/definitions/getConfigRequest"
          in: body
          name: body
      responses:
        200:
          description: 200 OK
          schema:
            type: object
        400:
          description: 400 Bad Request
          schema:
            $ref: "#/definitions/errorResponse"
        500:
          description: 500 Internal Server Error  
          schema:
            $ref: "#/definitions/errorResponse"  
tags: []
definitions:
  errorResponse:
    properties:
      error:
        type: string
        example: "error message"
  getConfigRequest:
    properties:
      type: 
        type: string
        example: "Develop.mr_robot"
      data:
        type: string
        example: "Database.processing"
      